### ISSUE TITLE
No menu item error deleting files in 2.9.2

### ISSUE THREAD

**Issue by tallthom** [elearningstudio/moodle-report_filetrash#6] opened 2015-09-17 10:58 UTC
Installed the 2.9 version of the plugin (supported from the Moodle.org plugins page) and found two issues:

1. There is no File Trash menu item under reports (or anywhere).
2. It gives an error when attempting to delete one orphaned audio file.

Debug info: 
Error code: sectionerror
Stack trace:
line 481 of /lib/setuplib.php: moodle_exception thrown
line 6771 of /lib/adminlib.php: call to print_error()
line 47 of /report/filetrash/delete.php: call to admin_externalpage_setup()

Please advise what other information I could gather to help solve this issue.

**Comment by ikolubr** [comment] 2015-09-24 15:35
Same here but on moodle 2.7+ and 1.2 file trash

**Comment by jlowe64** [comment] 2015-09-30 10:35
I'm having the same issue in 2.9.1+, also when I go directly to the page /report/filetrash/index.php. I couldn't get any debug info on the page. The page also intermittently logs me out of the site.

**Comment by jlowe64** [comment] 2015-09-30 10:45
I was able to force pull the following error:

Potential coding error: Unexpected output whilst processing AJAX request. This could be caused by trailing whitespace. Output received: '\r\n<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>'

**Comment by jlowe64** [comment] 2015-09-30 11:03
With further testing, the plugin seems to work, but it's hanging on the index page because it's checking a very large file storage. Would be good to get some indication that this is happening.

Also because there's no report/filetrash link in the admin menu, the plugin crashes when deleting files.

Default exception handler: Section error! Debug: \nError code: sectionerror\n* line 463 of /lib/setuplib.php: moodle_exception thrown\n* line 6770 of /lib/adminlib.php: call to print_error()\n* line 47 of /report/filetrash/delete.php: call to admin_externalpage_setup()\n

**Comment by elearningstudio** [comment] 2015-10-24 15:18
I believe the missing report link and sectionerror issues are now fixed (on the master branch)

**Closed** 2015-10-24 15:17 UTC

**Comment by elearningstudio** [comment] 2015-10-24 15:21
To speed the plugin up, go to Site Admin > Plugins > Reports > File Trash and make sure "Show file extensions in report?" is unticked

If that doesn't help I expect you probably have a very large site with lots of files.
